resources:
- ../../base
patchesJson6902:
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: nginx
  path: ingress_patch.yaml
commonLabels:
  app: dev-nginx
namespace: dev
configMapGenerator:
- name: nginx
  behavior: merge
  literals:
  - ENV=dev