apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:
  default.conf: |
    log_format json_combined escape=json '{ "time_local": "$time_local", '
        '"remote_addr": "$remote_addr", '
        '"remote_user": "$remote_user", '
        '"request": "$request", '
        '"status": "$status", '
        '"body_bytes_sent": "$body_bytes_sent", '
        '"request_time": "$request_time", '
        '"http_referrer": "$http_referer", '
        '"http_user_agent": "$http_user_agent" }';
    error_log stderr;

    server {
        access_log /var/log/nginx/access.log json_combined;

        listen   80;
        index index.html index.htm;
        sendfile off;

        gzip on;
        gzip_static on;
        gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
        gzip_proxied  any;
        gzip_vary on;

        location / {
            try_files $uri /index.html;
        }
    }

    server {
      listen 8008;
      server_name localhost;

      access_log off;
      allow 127.0.0.1;
      deny all;

      location /nginx_status {
        stub_status on;
      }
    }
