apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  labels:
    app: service-b
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - name: service-b
        image: swr.tr-west-1.myhuaweicloud.com/trc-sdlc-prod/service-b:master-f4385b5
        ports:
        - containerPort: 8080