apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: service-b
spec:
  template:
    spec:
      containers:
      - name: service-b
        image: swr.tr-west-1.myhuaweicloud.com/trc-sdlc-prod/service-b:master-f4385b5
    